### ISSUE TITLE
Status (Now Playing)

### ISSUE THREAD

**Issue by devz3ro** [zynine-/HDHRViewerV2.bundle#31]
This is more of a feature request than an issue.

Is there anyway to have what is being watched show up in the "Now Playing" section of Plex? It currently works for Android phone clients only, from what I've been able to tell. Android TV, Roku, and Web client(s) report nothing being played.

Thanks in advance.

**Comment by zynine-** [comment]
Nothing I can do about it I think.

**Comment by devz3ro** [comment]
Alright, thanks for looking into it.
