### ISSUE TITLE
Stream not starting

### ISSUE THREAD

**Issue by peperunas** [zynine-/HDHRViewerV2.bundle#32]
I followed all your directions but I still can't watch any channel from my HDHomeRun.
It just sits there "buffering", no life signs.

I tried with different browsers (with and without HTML5 player), even with the iOS application through Chromecast stream (main feature I'm interested in).
The setup is quite powerful: i5 6400 w/ GTX 1080 and 16 GB RAM.

**Comment by zynine-** [comment]
Can you attach the log files?

**Comment by peperunas** [comment]
Not using it anymore so I can't provide the debug logs, I'm sorry.
