### ISSUE TITLE
urllib2_new.URLError

### ISSUE THREAD

**Issue by scalhoun** [zynine-/HDHRViewerV2.bundle#33]
Anyone seen this error yet when loading channels?

```
AllChannelsMenu(0);&lt;type 'exceptions.NameError'&gt;: ("global name 'info' is not defined",): global name 'info' is not defined
```

**Comment by scalhoun** [comment]
Update.  I used master, just switched over to 0.9.1.

When loading channels:

```
<class 'urllib2_new.URLError'>: (timeout('timed out',),): <urlopen error timed out>
```

**Comment by zynine-** [comment]
Can you attach the logs?
What model of hdhomerun do you have?

**Comment by scalhoun** [comment]
No idea what I did but I tried it again today and it works perfect.  I did notice it was not showing my channel count initially but it is now.
