### ISSUE TITLE
No Audio on PlexConnect (AppleTV3 inofficial Client)

### ISSUE THREAD

**Issue by rix1337** [zynine-/HDHRViewerV2.bundle#35]
I know this type of issue is not very helpful, but I wanted to post it anyway:

On my AppleTV (through PlexConnect):

-SD Video Streams are working, but not their audio.
-HD Streams completely fail to be viewable.

Audio for SD was working on the old x.7.x builds.

Let me know how to help debugging this.

Good Job on the whole bundle!

**Comment by zynine-** [comment]
Logs and system specs would help.

**Comment by rix1337** [comment]
Moved to fire tv...
