### ISSUE TITLE
Unable to find HDHomeRun plugin

### ISSUE THREAD

**Issue by sdetweil** [zynine-/HDHRViewerV2.bundle#40]
I have PMS running, DVR beta Version 2.12.5 .  my HDHomerun is not here yet. 
Plex (on ubuntu 14.04) runs fine and I download content to view offline. 

now want to add live HDHomerun. 
cloned repo, ran the install_ubuntu.sh
restarted PMS..  but don't see the plugin to adjust settings anywhere. 

don't see the HDHomeRun icon anywhere on my plex players (android, web or roku)

what am I supposed to see? (the screen shots are interesting, but no context of how to get there)

**Comment by andrewconnell** [comment]
Instructions in the readme are pretty clear. I did method 2 and worked perfectly

**Comment by sdetweil** [comment]
I did approach 3, which is the script that does approach 2. 
I changed the owner/group to match the other plugins (need sudo to copy into /var/lib)

and then? I verified the files were copied, and inspected the structure of the files, and they look similar to the other plugins in the folder. 

it doesn't say restart PMS. It doesn't say, open Plex, go to Channels, or TV Shows, or Settings. 

**2. Initial Plug-in Settings/Preferences

Most Plex clients can't access the Plug-in Settings/Preferences. Use Plex/Web to configure it.**

I am on the machine with PMS, and I bring up my browser to access... (Plex/Web)
there is no mention of the Plugin.  I look thru the logs, and there is no mention of the plugin.

**3. 
Now try using the HDHR Viewer 2 again.**

again, I do not see anything  called "the HDHR Viewer 2"

**Comment by sdetweil** [comment]
Ok, resolved.. 

1. the Linux script copies to /var/lib, while the others copy relative to the user
changing the script to use 
**cp -R . "~/Library/Application Support/Plex Media Server/Plug-ins/HDHRViewerV2.bundle/"**
like the OSX script put the files in the right place. 
I found this by installing a plugin that was NOT in the /var/lib path and then looking for it. 
I didn't know where the directory structure for plex was stored.. used it for a year, never needed to know..

2. the readme should add
  after copying the files,  open the Plex UI via your browser, and select Channels, you should see the HDHR Viewer icon in the channel list.  If not, you have not installed the plugin in the correct location. 

pull request created to add these updates
