### ISSUE TITLE
"Conversion encoder or decoder not found"

### ISSUE THREAD

**Issue by HiNsKeY** [zynine-/HDHRViewerV2.bundle#44]
Getting a "Conversion encoder or decoder not found" when attempting to play any channels. I have followed the setup procedure as described in the setup guide and this is still occurring. I have also tried disabling the HTML5 player and this has not helped.

**Comment by zynine-** [comment]
HDHomeRun Model and Firmware?
And What Browser are you using?

**Comment by HiNsKeY** [comment]
HDHR4-2DT
20161117
I have only just set this HDHomeRun Connect up so the firmware should be up to date

**Comment by HiNsKeY** [comment]
Google Chrome

**Comment by devz3ro** [comment]
"Playback was not possible: Conversion encoder or decoder not found" is definitely related to H264. I am running PMS 1.4.2 with HDHR Viewer V2 v0.9.13. Tested the following using the latest hdhomerun firmware and an Nvidia Shield (Android TV) box.

This is from a 1 sec clip taken from my hdhomerun that **will not** play (channel with codec h264):
`<Media videoResolution="1080" id="525732" duration="1308" bitrate="5773" width="1920" height="1080" aspectRatio="1.78" audioChannels="6" audioCodec="ac3" videoCodec="h264" container="mpegts" videoFrameRate="NTSC" videoProfile="high">`

This is from a 1 sec clip taken from my hdhomerun that **will** play (channel with codec mpeg2video):
`<Media videoResolution="1080" id="81366" duration="1325" bitrate="18546" width="1920" height="1080" aspectRatio="1.78" audioChannels="6" audioCodec="ac3" videoCodec="mpeg2video" container="mpegts" videoFrameRate="NTSC" videoProfile="main">`

**Comment by HiNsKeY** [comment]
I have updated to the latest version and am now able to play HD channels without sound. Both the downloaded segments (SD and HD) work fine but the streams do not. Log file is attached.
[Plex Media Server.zip](https://github.com/zynine-/HDHRViewerV2.bundle/files/810915/Plex.Media.Server.zip)

**Comment by zynine-** [comment]
use 0.9.16
and provide plugin logs. thanks.

**Comment by HiNsKeY** [comment]
I am already using 0.9.16. Plugin logs attached.
[com.plexapp.plugins.hdhrviewer.v2.zip](https://github.com/zynine-/HDHRViewerV2.bundle/files/811576/com.plexapp.plugins.hdhrviewer.v2.zip)

**Comment by zynine-** [comment]
Botched release. Please use 0.9.17

**Comment by HiNsKeY** [comment]
Updated and the issue is fixed. Thanks
