### ISSUE TITLE
Both tuners in use error message (enhancement)

### ISSUE THREAD

**Issue by wahlmanj** [zynine-/HDHRViewerV2.bundle#55]
Could there be a message when both tuners are in use instead of a endless progress spinner?

Same result testing on plexweb and atv4 client using hdhomerun connect.

**Comment by zynine-** [comment]
Yes/No. Normal behavior.

At most I can only show a warning message before user hits the play button. I can't prevent the endless spinner.

**Comment by wahlmanj** [comment]
That works also thx!

**Comment by zynine-** [comment]
implemented in version 1.1.0
