### ISSUE TITLE
Channel Guide Problems (XMLTV FILE) seems to ignore xml file?

### ISSUE THREAD

**Issue by wazerstar** [zynine-/HDHRViewerV2.bundle#65]
I'm using Dane22 plugin to grab danish provider epg feed

http://forums.plex.tv/discussion/248011/rel-epg-dk/p1

**- com.plexapp.plugins.hdhrviewer.v2.log**
[com.plexapp.plugins.hdhrviewer.v2.log](https://github.com/zynine-/HDHRViewerV2.bundle/files/1963205/com.plexapp.plugins.hdhrviewer.v2.log)

**- http://hdhomerun_ip/lineup.json**
https://pastebin.com/hTd1cN3M

**- copy of the xmltv.xml**
[epg.zip](https://github.com/zynine-/HDHRViewerV2.bundle/files/1963213/epg.zip)

**Comment by zynine-** [comment]
Updates required to the other plug-in:
https://github.com/ukdtom/epg-dk.bundle/pull/24
